WIP ical_support: weird icalcomponent_get_utc_timespan complaint
GCC static analyser complains that the year field of due and created
are uninitialized, but only when memcpying them over period.end, even
though it might have just successfully memcpy'd it over period.start
without complaint.

Even weirder: replacing the memcpy's with assignments stops it
complaining, even though it should not have made any difference.

Might be a GCC bug?  But I need to shut it up to get on with fixing
the real complaints...

gcc (Debian 12.2.0-14) 12.2.0

imap/ical_support.c: In function 'icalcomponent_get_utc_timespan':
imap/ical_support.c:1223:25: error: use of uninitialized value '*(unsigned char (*)[40])((char *)&due + offsetof(struct icaltimetype, year))' [CWE-457] [-Werror=analyzer-use-of-uninitialized-value]
 1223 |                         memcpy(&period.end, &due, sizeof(struct icaltimetype));

...

imap/ical_support.c:1251:25: error: use of uninitialized value '*(unsigned char (*)[40])((char *)&created + offsetof(struct icaltimetype, year))' [CWE-457] [-Werror=analyzer-use-of-uninitialized-value]
 1251 |                         memcpy(&period.end, &created, sizeof(struct icaltimetype));