ical_support: include caldav_db.h
fixes compile errors due to undeclared symbols:

> imap/ical_support.c: In function ‘icalcomponent_remove_invitee’:
> imap/ical_support.c:114:36: error: ‘ICAL_VPOLL_COMPONENT’ undeclared (first use in this function)
> imap/ical_support.c:114:36: note: each undeclared identifier is reported only once for each function it appears in

... etc