Allow cyrus to compile Sphinx documentation with Sphinx version 4..0 or greater
When compiling cyrus-imap 3.8.0 on debian 12 with Sphinx documentation  cyrus  fails to compile with the following  error:

Exception occurred:
|   File "/usr/lib/python3/dist-packages/docutils/writers/manpage.py", line 171, in __init__
|     self.settings = settings = document.settings
| AttributeError: 'CyrusManualPageBuilder' object has no attribute 'settings'

Cause: 

CyrusManualPageTranslator inherits from Sphinx' ManualPageTranslator and calls the super-class constructor as follows:

 BaseTranslator.__init__(self, builder, *args, **kwds)

However, starting with Sphinx 2.0 it should be called with document as the first argument and builder as the second one [1]. The old way of calling it
raised a warning for some time and was completely removed in Sphinx 4.0.